stages:
  - build
  - deploy

variables:
  HUGO_VERSION: "0.80.0"

pages:
  image: debian
  stage: build
  only:
    - master
  before_script:
    - apt-get update && apt-get install -y wget
    - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb"
    - dpkg -i hugo_extended_${HUGO_VERSION}_Linux-64bit.deb
    - rm hugo_extended_${HUGO_VERSION}_Linux-64bit.deb
  script:
    - hugo
  artifacts:
    paths:
      - public

